//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int rowid { get; set; }
        public Nullable<bool> is_validate { get; set; }
        public string member_no { get; set; }
        public string member_name { get; set; }
        public string member_type_no { get; set; }
        public string member_password { get; set; }
        public string gender_code { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string contact_zip { get; set; }
        public string contact_address { get; set; }
        public string validate_code { get; set; }
        public string remark { get; set; }
    }
}
