//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int rowid { get; set; }
        public bool is_enabled { get; set; }
        public string module_no { get; set; }
        public string program_no { get; set; }
        public string program_name { get; set; }
        public string program_type_no { get; set; }
        public string area_name { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string parameter_value { get; set; }
        public string remark { get; set; }
    }
}
