//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Securitys
    {
        public int rowid { get; set; }
        public string account_no { get; set; }
        public string module_no { get; set; }
        public string program_no { get; set; }
        public bool is_add { get; set; }
        public bool is_edit { get; set; }
        public bool is_delete { get; set; }
        public bool is_print { get; set; }
        public bool is_upload { get; set; }
        public bool is_download { get; set; }
        public bool is_confirm { get; set; }
        public bool is_undo { get; set; }
        public string remark { get; set; }
    }
}
